package com.backenddynamouser.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "userAccount")
public class UserAccount {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute
    private String userName;

    @DynamoDBAttribute
    private Long userPhone;

    @DynamoDBAttribute
    private Long userCpf;

    @DynamoDBAttribute
    private Long userRg;

    @DynamoDBAttribute
    private String userEndereco;

    @DynamoDBAttribute
    private String userTipoConta;

    @DynamoDBAttribute
    private String userEmail;
}
