package com.backenddynamouser.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "userAccount")
public class UserAccount {


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute
    private String nome;

    @DynamoDBAttribute
    private String tel;

    @DynamoDBAttribute
    private String cpf;

    @DynamoDBAttribute
    private String rg;

    @DynamoDBAttribute
    private String end;

    @DynamoDBAttribute
    private String tipodeconta;

    @DynamoDBAttribute
    private String email;



//    public UserAccount( String userId, String nome, String tel, String cpf, String rg, String end, String tipodeconta,
//                        String email){
//        this.userId = userId;
//        this.nome = nome;
//        this.tel = tel;
//    }
}
